### ISSUE TITLE
Python + tensorflow +... versions for stable Splinedist training

### ISSUE THREAD

**Issue by lucpaul** [uhlmanngroup/splinedist#11]
Hi, 
I am just trying to run SplineDist locally in a conda environment, in pycharm. Do you have advice on the latest compatible versions of the required python packages (especially tensorflow etc.) to train a SplineDist model from scratch on my dataset? Is there a requirements file that would list these?

Thanks a lot.

**Comment by sohmandal** [comment]
Hi @lucpaul,

Attached .yml file contains the dependencies to set up a conda environment for SplineDist. Please let me know if this does not work for your need. 
[splinedist.yml.txt](https://github.com/uhlmanngroup/splinedist/files/9895791/splinedist.yml.txt)

**Comment by lucpaul** [comment]
Thanks, that was quite helpful.
