### ISSUE TITLE
Example script/notebook available for pre-trained models?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [uhlmanngroup/splinedist#12]
Hello team, thanks for this repo! I was wondering if you have an example script that shows how to run the [pre-trained models](https://doi.org/10.5281/zenodo.7193306) on example images?

**Comment by sohmandal** [comment]
Hi @ajinkya-kulkarni, thank you for your interest in SplineDist. 

If you want to do just inference with SplineDist on a set of images, you might like to follow the [prediction notebook](https://github.com/uhlmanngroup/splinedist/blob/main/prediction.ipynb) in the repo. First, you need to update the path to your data in the second cell (from section 'Data'). Then in the fourth cell (from section 'Load trained model') of this notebook, please assign the relevant weight directory name (such as bbbc038_8 from our [pre-trained models](https://doi.org/10.5281/zenodo.7193306)) as the `name` parameter.  Please make sure that you keep the weight directory inside the `models` sub-directory inside the SplineDist root directory. If you are using SplineDist for the first time after cloning the repo, this sub-directory will not be there. You can either create it on your own or you can initiate a training session using the training notebook, which will create this `models` sub-directory at its proper place for you. 

Hope this is helpful.

**Comment by sohmandal** [comment]
Closing this issue now because of inactivity. Please feel free to reopen it.
