### ISSUE TITLE
Will Splinedist go 3D

### ISSUE THREAD

**Issue by jbogomolovas2** [uhlmanngroup/splinedist#13]
First of all this is great tool! 
Just wondering are you planning, o maybe you already have/testing Splinedist in 3D?

Regards,
Julius

**Comment by sohmandal** [comment]
Hi @jbogomolovas2, thank you for your interest in SplineDist. We are currently working on developing the 3D version of SplineDist and we hope to release it in the future.

**Comment by jbogomolovas2** [comment]
Awesome! Looking forward to 3D option!
