### ISSUE TITLE
predict_instances_big() needs fixing

### ISSUE THREAD

**Issue by loicsauteur** [uhlmanngroup/splinedist#3]
Hi,

I tired to use the `model.predict_instances_big()`to overcome some GPU memory issues (using a small GPU)...

`splinedist\big.py` tries to `from .geometry import polygons_to_label, polyhedron_to_label`
`polyhedron_to_label` is a function that does not exist.

It should be replaced with `from .geometry import polygons_to_label`

bests

**Comment by sohmandal** [comment]
Hi, thanks for pointing out this issue. It has been sorted out now in 8eeff9e9541977ab327d49cd6d6f55da76fa7962.

**Comment by sohmandal** [comment]
Closing this issue now. Please feel free to reopen it, if your issue is not solved.
